## **Fortgeschrittene Softwaretechnik (WiSe2122) - Pet Project**
Cancer Cell Analysis - Lung Cancer

## **Import Libraries**
Importing all the libraries I'm using in this project

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import classification_report

## **Upload files**
Uploading the data file which contains the datasets in them 

In [2]:
from google.colab import files
uploaded = files.upload()

Saving datasets.xlsx to datasets.xlsx


Read the dataset using pandas

In [3]:
data = pd.read_excel('datasets.xlsx')
data.head()

Patient Id  Age  Gender  ...  Dry Cough  Snoring   Level
0         P1   33       1  ...          3        4     Low
1        P10   17       1  ...          7        2  Medium
2       P100   35       1  ...          7        2    High
3      P1000   37       1  ...          7        5    High
4       P101   46       1  ...          2        3    High

[5 rows x 25 columns]

## **Basic data analysis**

In [4]:
data.shape

(1000, 25)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Patient Id                1000 non-null   object
 1   Age                       1000 non-null   int64 
 2   Gender                    1000 non-null   int64 
 3   Air Pollution             1000 non-null   int64 
 4   Alcohol use               1000 non-null   int64 
 5   Dust Allergy              1000 non-null   int64 
 6   OccuPational Hazards      1000 non-null   int64 
 7   Genetic Risk              1000 non-null   int64 
 8   chronic Lung Disease      1000 non-null   int64 
 9   Balanced Diet             1000 non-null   int64 
 10  Obesity                   1000 non-null   int64 
 11  Smoking                   1000 non-null   int64 
 12  Passive Smoker            1000 non-null   int64 
 13  Chest Pain                1000 non-null   int64 
 14  Coughing of Blood        

In [6]:
data.describe(include='all')

Patient Id          Age       Gender  ...    Dry Cough      Snoring  Level
count        1000  1000.000000  1000.000000  ...  1000.000000  1000.000000   1000
unique       1000          NaN          NaN  ...          NaN          NaN      3
top            P1          NaN          NaN  ...          NaN          NaN   High
freq            1          NaN          NaN  ...          NaN          NaN    365
mean          NaN    37.174000     1.402000  ...     3.853000     2.926000    NaN
std           NaN    12.005493     0.490547  ...     2.039007     1.474686    NaN
min           NaN    14.000000     1.000000  ...     1.000000     1.000000    NaN
25%           NaN    27.750000     1.000000  ...     2.000000     2.000000    NaN
50%           NaN    36.000000     1.000000  ...     4.000000     3.000000    NaN
75%           NaN    45.000000     2.000000  ...     6.000000     4.000000    NaN
max           NaN    73.000000     2.000000  ...     7.000000     7.000000    NaN

[11 rows x 25 columns]

Drop the Patient ID feature as the Patient Id feature has no relation with the Lung Cancer level

In [7]:
data.drop(columns=['Patient Id'], axis = 1, inplace=True)
data.head()

Age  Gender  Air Pollution  ...  Dry Cough  Snoring   Level
0   33       1              2  ...          3        4     Low
1   17       1              3  ...          7        2  Medium
2   35       1              4  ...          7        2    High
3   37       1              7  ...          7        5    High
4   46       1              6  ...          2        3    High

[5 rows x 24 columns]

Feature mapping 
- Before feature mapping lets do value count on input "Level"

In [8]:
data['Level'].value_counts()

High      365
Medium    332
Low       303
Name: Level, dtype: int64

In [9]:
level_mapping = {'Low':1, 'Medium':2, 'High':3}
data.Level = data['Level'].map(level_mapping)
data.head()

Age  Gender  Air Pollution  ...  Dry Cough  Snoring  Level
0   33       1              2  ...          3        4      1
1   17       1              3  ...          7        2      2
2   35       1              4  ...          7        2      3
3   37       1              7  ...          7        5      3
4   46       1              6  ...          2        3      3

[5 rows x 24 columns]

Splitting the dataset into input and output features so that we can train our model

In [10]:
array = data.values
X = array[:, 0:23]
Y = array[:, 23]

## **Univariate Feature Selection**
- For this dataset we will perform univariate feature selection using chi2 as our score function.

In [11]:
def feature_extraction(score_function, k):
  test = SelectKBest(score_func=score_function, k=k)
  fit = test.fit(X, Y)
  features = fit.transform(X)

  return features

In [12]:
features = feature_extraction(chi2, 10)
print(features)

[[2 4 3 ... 2 4 3]
 [3 1 4 ... 2 3 1]
 [4 5 5 ... 4 8 8]
 ...
 [4 5 5 ... 4 8 8]
 [6 8 7 ... 7 9 3]
 [6 5 5 ... 4 8 8]]


## **Building our model**
- Seperating dataset into training and the validation set using train_test_split().

In [13]:
x_train, x_test, y_train, y_test = train_test_split(features, Y, test_size=0.33, random_state=0)

### Logistic Regression
building the model

In [14]:
def create_model1(x_train, y_train):
  Model = LogisticRegression()
  Model.fit(x_train, y_train)

  return Model

In [15]:
Model1 = create_model1(x_train, y_train)

After we built the model, we  evaluate its performance using score function. 

In [16]:
score = Model1.score(x_test, y_test)
print(score)

0.9393939393939394


**Test**
- did a simple test Since I used ML in my coding it gives automatic testing when I get the accuracy. 

In [17]:
assert score * 100 > 90, print("FAILED, accuracy is below 90%")
print("PASSED, accuracy is above 90% : ", score * 100)

PASSED, accuracy is above 90% :  93.93939393939394


In [18]:
predictions1 = Model1.predict(x_test)

In [19]:
mean_absolute_error(y_test, predictions1)

0.06060606060606061

In [20]:
print(classification_report(y_test, predictions1))

              precision    recall  f1-score   support

           1       0.95      0.87      0.91       113
           2       0.86      0.95      0.91       101
           3       1.00      1.00      1.00       116

    accuracy                           0.94       330
   macro avg       0.94      0.94      0.94       330
weighted avg       0.94      0.94      0.94       330



Using K-Fold

In [21]:
def k_fold(Model, num_folds, seed, scoring):
  kfold = KFold(n_splits=num_folds, random_state=seed)
  cv_results = cross_val_score(Model, x_train, y_train, scoring=scoring, cv=kfold)
  msg = '%f (%f)'%(cv_results.mean(), cv_results.std())
  print(msg)

In [22]:
# Test options and evaluation metric
num_folds = 10
seed = None
scoring = 'accuracy'

k_fold(Model1, num_folds, seed, scoring)

0.931343 (0.031450)


### SVM (support vector Machine)

In [23]:
def create_model2(x_train, y_train):
  Model = SVC(kernel='linear')
  Model.fit(x_train, y_train)

  return Model

In [24]:
Model2 = create_model2(x_train, y_train)

After we built the model, we  evaluate its performance using score function.

In [25]:
score = Model2.score(x_test, y_test)
print(score)

0.9545454545454546


Test

In [26]:
assert score * 100 > 90, print("FAILED, accuracy is below 90%")
print("PASSED, accuracy is above 90% : ", score * 100)

PASSED, accuracy is above 90% :  95.45454545454545


In [27]:
predictions2 = Model2.predict(x_test)

In [28]:
# mean absolute error
mean_absolute_error(y_test, predictions2)

0.045454545454545456

Using K-Fold

In [29]:
# Test options and evaluation metric
num_folds = 10
seed = None
scoring = 'accuracy'

k_fold(Model2, num_folds, seed, scoring)

0.934328 (0.026866)


Classification report for SVM

In [30]:
print(classification_report(y_test, predictions2))

              precision    recall  f1-score   support

           1       1.00      0.87      0.93       113
           2       0.87      1.00      0.93       101
           3       1.00      1.00      1.00       116

    accuracy                           0.95       330
   macro avg       0.96      0.96      0.95       330
weighted avg       0.96      0.95      0.95       330

